server:
  port: 80

spring:
  application:
    name: SpringBootTemplate
  servlet:
    multipart:
      max-file-size: 50MB # 限制上传的单个文件的大小
      max-request-size: 500MB # 限制单次请求的文件的总大小
  profiles:
    active: @profile.active@
  main:
    banner-mode: off # 关闭启动项目时的 springboot 图标
    allow-circular-references: true # 允许循环引用其他类
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 支持 Ant 风格的路径匹配

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # mapper 的 xml 文件路径
  global-config:
    db-config:
      id-type: assign_id # 雪花算法生成 id
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: off # 关闭启动项目时的 mybatis-plus 图标
  configuration:
    auto-mapping-behavior: partial # 开启结果集自动映射
    map-underscore-to-camel-case: true # 开启驼峰映射

redis:
  database: project
  key:
    user: 'ums:user'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

jwt:
  tokenHeader: Authorization # JWT 存储的请求头
  secret: project-user-secret # JWT 加解密使用的密钥
  expiration: 604800 # JWT 的超期限时间 (60 * 60 * 24 * 7 = 1周)
  tokenHead: 'Bearer ' # JWT 负载中拿到开头

knife4j:
  enableSecurity: true  # 开启登录认证
  enableKnife4j: true  # 开启增强功能
  basePackage: com.project.modules # 基础扫描包范围
  serviceUrl: http://localhost:80/doc.html  # 服务器接口文档访问地址
  title: project 项目接口文档  # 接口文档标题
  description: 接口文档查看和接口调试  # 接口文档描述
  version: v1.0  # 接口文档版本
  contactName: Qing2514 # 联系人
  contactUrl: http://localhost:80 # 联系人网站
  contactEmail: admin@163.com # 联系人邮箱

sm2:
  privateKey: 64c9a9aacfcd1b9003b70c822985c003453ec9cfbcad607d8bd8109a5139bec0 # 64位私钥
  publicKey: 0207f8846e407e92ade01da0d9a81f472b5d380686776459b0c9b34adae9b240d1 # 66位公钥，前两位为标记

sm4:
  key: 1234567812345678 # 16位秘钥

secure:
  ignored:
    urls: # 安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/register
      - /admin/login
      - /admin/logout
      - /admin/refreshToken
